# Generated by Django 5.0.7 on 2024-07-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridparts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prefab_images/'),
        ),
    ]
