# Generated by Django 5.0.7 on 2024-07-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0002_gridparts_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapsetup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="map_images/"),
        ),
    ]
