# Generated by Django 5.0.7 on 2024-08-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_mapsetup_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefabsconveyor',
            old_name='speed',
            new_name='speed1',
        ),
    ]
