# Generated by Django 5.0.7 on 2024-08-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_speed_prefabsconveyor_speed1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gridparts',
            old_name='speed',
            new_name='speed1',
        ),
        migrations.AddField(
            model_name='gridparts',
            name='cm_head',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='cm_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='cm_tail',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='encoder_fitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='group_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='head_pec_fitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='head_pect_distance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='ramp_down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='ramp_up',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='speed2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='speed3',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='stand_by_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='start_position_fwd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='start_position_rev',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='tail_pec_fitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gridparts',
            name='tail_pect_distance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='cm_head',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='cm_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='cm_tail',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='encoder_fitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='group_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='head_pec_fitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='head_pect_distance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='ramp_down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='ramp_up',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='speed2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='speed3',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='stand_by_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='start_position_fwd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='start_position_rev',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='tail_pec_fitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prefabsconveyor',
            name='tail_pect_distance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gridparts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='prefabsconveyor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
